version: "3.5"
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=rinha
      - MYSQL_USER=rinha
      - MYSQL_PASSWORD=rinha
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql