version: "3.5"
services:
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=rinha
      - MYSQL_USER=rinha
      - MYSQL_PASSWORD=rinha
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST="%"
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


